##开发是打开注释项 ---------------------------
###集成时需要配置如下数据项
##server:
##  session:
##    timeout: 30
##
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/exchange?useUnicode=true&characterEncoding=UTF-8
#    username: root
#    password: root
#    driver-class-name: com.mysql.jdbc.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL5Dialect
#
#  session:
#    store-type: redis
#  redis:
#    host: 127.0.0.1
#    database: 0
#    port: 6379
#
#
#
## 自定义提示信息，根据需要进行配置（可选）
##com:
##  guns21:
##    security:
##      message:
##        access-denied: 没有访问权限！
##        password-error: 用户密码错误！
##        login-success: 登录成功！
##        logout-success: 登出成功！
##        user-not-exist: 用户不存在！
##        login-error: 请提交正确的用户信息！
##      permit-pages: /home,/static/**
##      login: /api/usermanage/v1/login
#
#
#
#
#
