package com.guns21.upload.provider;

import java.io.Serializable;

public class Attachment implements Serializable {

    public static Attachment newAttachment() {
        return new Attachment();
    }
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_attach.attach_id
     *
     * @mbggenerated
     */
    private Integer attachId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_attach.app_name
     *
     * @mbggenerated
     */
    private String appName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_attach.table
     *
     * @mbggenerated
     */
    private String table;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_attach.row_id
     *
     * @mbggenerated
     */
    private Integer rowId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_attach.attach_type
     *
     * @mbggenerated
     */
    private String attachType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_attach.uid
     *
     * @mbggenerated
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_attach.ctime
     *
     * @mbggenerated
     */
    private Integer ctime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_attach.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_attach.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_attach.size
     *
     * @mbggenerated
     */
    private String size;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_attach.extension
     *
     * @mbggenerated
     */
    private String extension;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_attach.hash
     *
     * @mbggenerated
     */
    private String hash;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_attach.private
     *
     * @mbggenerated
     */
    private Boolean privateType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_attach.is_del
     *
     * @mbggenerated
     */
    private Boolean isDel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_attach.save_path
     *
     * @mbggenerated
     */
    private String savePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_attach.save_name
     *
     * @mbggenerated
     */
    private String saveName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_attach.save_domain
     *
     * @mbggenerated
     */
    private Byte saveDomain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_attach.from
     *
     * @mbggenerated
     */
    private Byte from;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_attach.width
     *
     * @mbggenerated
     */
    private Integer width;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ts_attach.height
     *
     * @mbggenerated
     */
    private Integer height;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ts_attach
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_attach.attach_id
     *
     * @return the value of ts_attach.attach_id
     *
     * @mbggenerated
     */
    public Integer getAttachId() {
        return attachId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_attach.attach_id
     *
     * @param attachId the value for ts_attach.attach_id
     *
     * @mbggenerated
     */
    public void setAttachId(Integer attachId) {
        this.attachId = attachId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_attach.app_name
     *
     * @return the value of ts_attach.app_name
     *
     * @mbggenerated
     */
    public String getAppName() {
        return appName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_attach.app_name
     *
     * @param appName the value for ts_attach.app_name
     *
     * @mbggenerated
     */
    public void setAppName(String appName) {
        this.appName = appName == null ? null : appName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_attach.table
     *
     * @return the value of ts_attach.table
     *
     * @mbggenerated
     */
    public String getTable() {
        return table;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_attach.table
     *
     * @param table the value for ts_attach.table
     *
     * @mbggenerated
     */
    public void setTable(String table) {
        this.table = table == null ? null : table.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_attach.row_id
     *
     * @return the value of ts_attach.row_id
     *
     * @mbggenerated
     */
    public Integer getRowId() {
        return rowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_attach.row_id
     *
     * @param rowId the value for ts_attach.row_id
     *
     * @mbggenerated
     */
    public void setRowId(Integer rowId) {
        this.rowId = rowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_attach.attach_type
     *
     * @return the value of ts_attach.attach_type
     *
     * @mbggenerated
     */
    public String getAttachType() {
        return attachType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_attach.attach_type
     *
     * @param attachType the value for ts_attach.attach_type
     *
     * @mbggenerated
     */
    public void setAttachType(String attachType) {
        this.attachType = attachType == null ? null : attachType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_attach.uid
     *
     * @return the value of ts_attach.uid
     *
     * @mbggenerated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_attach.uid
     *
     * @param uid the value for ts_attach.uid
     *
     * @mbggenerated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_attach.ctime
     *
     * @return the value of ts_attach.ctime
     *
     * @mbggenerated
     */
    public Integer getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_attach.ctime
     *
     * @param ctime the value for ts_attach.ctime
     *
     * @mbggenerated
     */
    public void setCtime(Integer ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_attach.name
     *
     * @return the value of ts_attach.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_attach.name
     *
     * @param name the value for ts_attach.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_attach.type
     *
     * @return the value of ts_attach.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_attach.type
     *
     * @param type the value for ts_attach.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_attach.size
     *
     * @return the value of ts_attach.size
     *
     * @mbggenerated
     */
    public String getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_attach.size
     *
     * @param size the value for ts_attach.size
     *
     * @mbggenerated
     */
    public void setSize(String size) {
        this.size = size == null ? null : size.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_attach.extension
     *
     * @return the value of ts_attach.extension
     *
     * @mbggenerated
     */
    public String getExtension() {
        return extension;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_attach.extension
     *
     * @param extension the value for ts_attach.extension
     *
     * @mbggenerated
     */
    public void setExtension(String extension) {
        this.extension = extension == null ? null : extension.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_attach.hash
     *
     * @return the value of ts_attach.hash
     *
     * @mbggenerated
     */
    public String getHash() {
        return hash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_attach.hash
     *
     * @param hash the value for ts_attach.hash
     *
     * @mbggenerated
     */
    public void setHash(String hash) {
        this.hash = hash == null ? null : hash.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_attach.private
     *
     * @return the value of ts_attach.private
     *
     * @mbggenerated
     */
    public Boolean getPrivateType() {
        return privateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_attach.private
     *
     * @param privateType the value for ts_attach.private
     *
     * @mbggenerated
     */
    public void setPrivateType(Boolean privateType) {
        this.privateType = privateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_attach.is_del
     *
     * @return the value of ts_attach.is_del
     *
     * @mbggenerated
     */
    public Boolean getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_attach.is_del
     *
     * @param isDel the value for ts_attach.is_del
     *
     * @mbggenerated
     */
    public void setIsDel(Boolean isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_attach.save_path
     *
     * @return the value of ts_attach.save_path
     *
     * @mbggenerated
     */
    public String getSavePath() {
        return savePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_attach.save_path
     *
     * @param savePath the value for ts_attach.save_path
     *
     * @mbggenerated
     */
    public void setSavePath(String savePath) {
        this.savePath = savePath == null ? null : savePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_attach.save_name
     *
     * @return the value of ts_attach.save_name
     *
     * @mbggenerated
     */
    public String getSaveName() {
        return saveName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_attach.save_name
     *
     * @param saveName the value for ts_attach.save_name
     *
     * @mbggenerated
     */
    public void setSaveName(String saveName) {
        this.saveName = saveName == null ? null : saveName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_attach.save_domain
     *
     * @return the value of ts_attach.save_domain
     *
     * @mbggenerated
     */
    public Byte getSaveDomain() {
        return saveDomain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_attach.save_domain
     *
     * @param saveDomain the value for ts_attach.save_domain
     *
     * @mbggenerated
     */
    public void setSaveDomain(Byte saveDomain) {
        this.saveDomain = saveDomain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_attach.from
     *
     * @return the value of ts_attach.from
     *
     * @mbggenerated
     */
    public Byte getFrom() {
        return from;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_attach.from
     *
     * @param from the value for ts_attach.from
     *
     * @mbggenerated
     */
    public void setFrom(Byte from) {
        this.from = from;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_attach.width
     *
     * @return the value of ts_attach.width
     *
     * @mbggenerated
     */
    public Integer getWidth() {
        return width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_attach.width
     *
     * @param width the value for ts_attach.width
     *
     * @mbggenerated
     */
    public void setWidth(Integer width) {
        this.width = width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ts_attach.height
     *
     * @return the value of ts_attach.height
     *
     * @mbggenerated
     */
    public Integer getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ts_attach.height
     *
     * @param height the value for ts_attach.height
     *
     * @mbggenerated
     */
    public void setHeight(Integer height) {
        this.height = height;
    }

}